drop

create table points
(
    id integer generated by default as identity constraint points_pkey primary key,
    user_id integer not null constraint points_user_id_fkey references users,
    contest_id integer not null constraint points_contest_id_fkey references contests,
    points integer not null,
    category text,
    description text,
    sabotage_id integer constraint points_sabotage_id_fkey references sabotage,
    win_id integer constraint points_win_id_fkey references win,
    date_created timestamp with time zone default now() not null
);