INSERT INTO public.sabotage
(sabotage, contest_id, date_created)
VALUES
    ('Eat McDonalds with your kids', 4, now()),
    ('No swimming', 4, now()),
    ('No alcohol', 4, now()),
    ('Eat Chinese food', 4, now()),
    ('Eat a serving of potatoes', 4, now()),
    ('Eat dessert', 4, now()),
    ('Drink alcohol', 4, now()),
    ('Eat a portion of pasta', 4, now()),
    ('Your kids decide what you eat', 4, now()),
    ('No hot showers', 4, now()),
    ('Eat a portion of rice', 4, now()),
    ('Drink a Venti starbucks', 4, now()),
    ('Get up with the kids and take them to school', 4, now()),
    ('Feed kids and pack them lunch', 4, now()),
    ('Get up at 7am', 4, now()),
    ('Eat cookie cake', 4, now()),
    ('Eat cheesecake', 4, now()),
    ('Cook using only one pan', 4, now()),
    ('Meal must include the color green', 4, now()),
    ('No looking at the scale', 4, now()),
    ('No practicing balancing on one leg', 4, now()),
    ('No cold showers', 4, now()),
    ('Eat breakfast', 4, now()),
    ('Take a shot', 4, now()),
    ('Eat drive thru/takeout/delivery', 4, now()),
    ('No final fantasy', 4, now()),
    ('Eat something different for dinner every night', 4, now()),
    ('No dessert', 4, now()),
    ('Take 1 hour me-time', 4, now()),
    ('Have a glass of milk', 4, now()),
    ('Order donuts', 4, now());

