INSERT INTO public.bingo_item
(bingo_item, date_created, contest_id)
VALUES
    ('Swim for 30 minutes', now(), 4),
    ('Go for a 30 minute run', now(), 4),
    ('Get 4000 steps in a day', now(), 4),
    ('Eat 5 servings of veggies in a day', now(), 4),
    ('Drink half your weight in oz. of water', now(), 4),
    ('Wake up early specifically to workout', now(), 4),
    ('Meditate for 30 minutes', now(), 4),
    ('Read for 30 minutes instead of phone use', now(), 4),
    ('Do a workout that involves your kids', now(), 4),
    ('Do a workout video', now(), 4),
    ('Get 10 hours of sleep', now(), 4),
    ('Do not workout for 3 days in a row', now(), 4),
    ('Order and eat takout/delivery', now(), 4),
    ('Get outside for 30 minutes', now(), 4),
    ('Cook and serve a meal for your family', now(), 4),
    ('Do something creative for 30 minutes', now(), 4),
    ('Take an uniterrupted bath', now(), 4),
    ('Communicate with a friend or relative you have not talked to in over 3 weeks', now(), 4),
    ('Date with spouse or friends (no kids)', now(), 4),
    ('30 minute yoga routine', now(), 4),
    ('Try a new/unique veggie', now(), 4),
    ('Eat dessert', now(), 4),
    ('Clean house for 30 minutes', now(), 4),
    ('Drink an alcoholic drink', now(), 4),
    ('Spend time with friends/non-immediate family', now(), 4),
    ('Go for a 30 minute walk', now(), 4),
    ('Use essential oils/aromatherapy', now(), 4),
    ('Stretch for 10 minutes', now(), 4),
    ('Take a nap for at least 30 minutes', now(), 4),
    ('Brush and floss your teeth twice a day (Meal in between)', now(), 4),
    ('Sit up straight when working/playing at the computer', now(), 4),
    ('Practice balancing on one leg for 10 minutes', now(), 4),
    ('Have a cup of tea', now(), 4),
    ('Bake something sweet with your kids', now(), 4),
    ('Eat asparagus', now(), 4),
    ('Eat a veggie you do not like', now(), 4),
    ('Special time with son and daughter (2 days)', now(), 4),
    ('Take a cold shower', now(), 4),
    ('Try a new recipie', now(), 4),
    ('Order and consume an item from the drive through', now(), 4),
    ('Drink a soda', now(), 4),
    ('Have sex', now(), 4),
    ('Workout 3 days in a row', now(), 4),
    ('Have an orgasm', now(), 4),
    ('Eat zucchini', now(), 4),
    ('Eat broccoli', now(), 4),
    ('Eat veggies with at least one meal 3 days in a row', now(), 4);
